# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20170119_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='capital',
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
